spring:
  datasource:
    url: jdbc:mysql://190.122.236.218:3307/sgeu_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: dbtester
    password: igsoftware1234__
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
