spring:
  datasource:
    url: jdbc:mysql://190.122.236.218:3306/sgeu_db?useSSL=false&serverTimezone=America/Argentina/San_Luis&connectionTimeZone=America/Argentina/San_Luis&allowPublicKeyRetrieval=true
    username: dbtester
    password: igsoftware1234__
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true